### ISSUE TITLE
Looking way to read custom extensions in OAS spec

### ISSUE THREAD

**Issue by arvind-agarwal** [exegesis-js/exegesis#10]
@jwalton I am trying to figure out a way to get the custom extensions from yaml file for the current path.

I was able to get it using, 

```
context.api.pathItemObject.get["x-rate-limit"]
```
Is this the recommended way of getting these custom extensions?

**Comment by jwalton** [comment]
This is probably the best way to get them, yeah.

I'm also right in the middle of documenting how plugins will work, so you
may find it easier to write an 'exegesis-plugin-rate-limiter' package.  ;)
I'll comment here when I get the docs pushed to master.

On May 14, 2018 07:42, "Arvind Agarwal" <notifications@github.com> wrote:

@jwalton <https://github.com/jwalton> I am trying to figure out a way to
get the custom extensions from yaml file for the current path.

I was able to get it using,

context.api.pathItemObject.get["x-rate-limit"]

Is this the recommended way of getting these custom extensions?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/exegesis-js/exegesis/issues/10>, or mute the thread

**Comment by arvind-agarwal** [comment]
super plugin system would be best. But beyond that still sometimes additional metadata is useful to be read in controllers instead of hardcoding them.

**Comment by jwalton** [comment]
This is exactly the intent behind the context.api object, so you're using
it right.  :)

On May 14, 2018 07:55, "Arvind Agarwal" <notifications@github.com> wrote:

super plugin system would be best. But beyond that still sometimes
additional metadata is useful to be read in controllers instead of
hardcoding them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/exegesis-js/exegesis/issues/10#issuecomment-388791086>,
or mute the thread

**Comment by jwalton** [comment]
[Plugin docs](https://github.com/exegesis-js/exegesis/blob/master/docs/Exegesis%20Plugins.md) are here.  And role support has been refactored out into it's own plugin [here](https://github.com/exegesis-js/exegesis-plugin-roles).  As usual, let me know if any of this is unclear, or if it doesn't fit your needs.y
