### ISSUE TITLE
Incorrectly failing validation under a weird condition

### ISSUE THREAD

**Issue by kf6kjg** [exegesis-js/exegesis#134]
I found this condition in my main API definition and implementation, and I've spent the last few hours carefully whittling it down to its core, excising anything that didn't change my pass-fail tests.

Below you'll find the two needed OpenAPI 3.0.1 definition files, and a Service typescript file. These provide the minimal test case and should exhibit the failure if placed in a boilerplate Exegesis project.  I've not tested doing that however.  What I have tested is that these files, as is, exhibit the symptoms within the project that I found the issue originally.

If I inline the contents of `outboard.yaml` into `openapi.yaml` the `test2` method of the service passes.  If I remove the unused `Breaker` entry from `openapi.yaml`, or do any of the other items I've marked in the two YAML files, the bug disappears.  Of course in my real API none of these changes are actually viable workarounds as far as I can tell at this point.

The error thrown is, after prettifying, the following:
```json
[
  {
    "message": "should be object",
    "location": {
      "in": "response",
      "name": "body",
      "docPath": "/paths/~1test/get/responses/200/content/application~1json/schema",
      "path": "/test/next"
    },
    "ajvError": {
      "keyword": "type",
      "dataPath": "/value/test/next",
      "schemaPath": "#/type",
      "params": {
        "type": "object"
      },
      "message": "should be object"
    }
  },
  {
    "message": "should be object",
    "location": {
      "in": "response",
      "name": "body",
      "docPath": "/paths/~1test/get/responses/200/content/application~1json/schema",
      "path": "/test/next"
    },
    "ajvError": {
      "keyword": "type",
      "dataPath": "/value/test/next",
      "schemaPath": "#/properties/value/definitions/1/type",
      "params": {
        "type": "object"
      },
      "message": "should be object"
    }
  },
  {
    "message": "should match exactly one schema in oneOf",
    "location": {
      "in": "response",
      "name": "body",
      "docPath": "/paths/~1test/get/responses/200/content/application~1json/schema",
      "path": "/test/next"
    },
    "ajvError": {
      "keyword": "oneOf",
      "dataPath": "/value/test/next",
      "schemaPath": "#/properties/next/oneOf",
      "params": {
        "passingSchemas": null
      },
      "message": "should match exactly one schema in oneOf"
    }
  }
]
```

I've added `.txt` to the file extensions to that I can attach them.
* [openapi.yaml.txt](https://github.com/exegesis-js/exegesis/files/4316576/openapi.yaml.txt)
* [outboard.yaml.txt](https://github.com/exegesis-js/exegesis/files/4316577/outboard.yaml.txt)
* [Service.ts.txt](https://github.com/exegesis-js/exegesis/files/4316611/Service.ts.txt)

**Comment by jwalton** [comment]
This is a good one.  :)

So, when we build a validator for a message body or a parameter, we use `ajv`.  We need to pass `ajv` a JSON schema object, so we have [extractSchema()](https://github.com/exegesis-js/exegesis/blob/d09afec2e949c46457278acde86e739cf2e1506f/src/utils/jsonSchema.ts#L85) which pulls out the schema object.  The schema can reference other parts of the JSON document through $refs, though, so we basically create a schema that looks like:

```js
{
  // Your top-level schema here
  definitions: {
    // All the sub-schemas we needed to extract to make this all work
  }
} 
```

In order to try to make this extracted schema  "pretty", we [try to use your existing object names](https://github.com/exegesis-js/exegesis/blob/d09afec2e949c46457278acde86e739cf2e1506f/src/utils/jsonSchema.ts#L51-L52) in the `definitions` section.  But, obviously, we could end up with two different objects both named "Foo" in different parts of the schema, so if we run into this case we [compute a new name](https://github.com/exegesis-js/exegesis/blob/d09afec2e949c46457278acde86e739cf2e1506f/src/utils/jsonSchema.ts#L53-L55).

Now, the problem here is after we load your example document through `json-schema-ref-parser`, we end up with something like this:

```js
{
                paths: {
                    '/test': {
                        get: {
                            responses: {
                                '200': {
                                    description: 'test.',
                                    content: {
                                        'application/json': {
                                            schema: {
                                                type: 'object',
                                                properties: {
                                                    test: {
                                                        $ref:
                                                            '#/definitions/LinkObject/properties/test/allOf/0',
                                                    },
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                definitions: {
                    LinkObject: {
                        type: 'object',
                        properties: {
                            test: {
                                allOf: [
                                    {
                                        type: 'object',
                                        properties: {
                                            next: {
                                                oneOf: [
                                                    {
                                                        $ref:
                                                            '#/definitions/LinkObject/properties/test/allOf/0/additionalProperties/anyOf/0',
                                                    },
                                                    {
                                                        $ref:
                                                            '#/definitions/LinkObject/properties/test/allOf/0/additionalProperties/anyOf/1',
                                                    },
                                                ],
                                            },
                                        },
                                        additionalProperties: {
                                            oneOf: [
                                                {
                                                    type: 'array',
                                                    items: { type: 'object' },
                                                },
                                                { type: 'object' },
                                            ],
                                        },
                                    },
                                ],
                            },
                        },
                    },
                },
            };
```

Notice that all the refs go to arrays.  So when we try to pick "nice names", the names are "0" and "1".  That first ref in the `paths` part goes to the `allOf`, so we pick "0" as the nice name for it, before we put anything into `definitions` we [recurse into the child](https://github.com/exegesis-js/exegesis/blob/d09afec2e949c46457278acde86e739cf2e1506f/src/utils/jsonSchema.ts#L59-L64).  Only, the child *also* tries to create a "nice name" of 0 when we try to do the first `oneOf`, and since we haven't actually written the schema we're in the middle of extracting into `ctx.result.definitions` yet, we go ahead and use "0".  Then when we finish extracting this subschema, we end up clobbering the "0" one level up.

You might think we could just reorder this - extract the child schema first, then pick a new name for it - this way we can't clobber child schemas.  The problem with this is that a fairly simple recursive schema will end up blowing your stack.  -_-  So instead, we're going to keep track of what names we pick seperately from `ctx.result.definitions`.  I'll have a fix in just a moment.  :)

**Comment by kf6kjg** [comment]
I thought you might find this an interesting one. :D  It was just so weird looking once I distilled it.

**Comment by jwalton** [comment]
You're finding all sorts of crazy corner cases.  :P  Keep it up, please.  :)
