### ISSUE TITLE
Validation error of request body when oneOf is used

### ISSUE THREAD

**Issue by pawelusfr** [exegesis-js/exegesis#140]
**Exegesis version used:**
exegesis-express 2.0.0 which has a dependency on exegesis resolved to 2.5.3

With this spec:
```yaml
info:
  title: Test
  version: 1.0.0
  description: 'Exegesis test'
openapi: 3.0.4
paths:
  '/exegesis':
    patch:
      summary: Exegesis test
      description: This will fail validation
      tags:
       - exegesis
      operationId: exegesisTest
      x-exegesis-controller: exegesis
      requestBody:
        description: Some data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestThis'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
components:
  schemas:
    TestThisOne:
      type: object
      properties:
        title:
          type: string
        refs:
          type: string
          nullable: true
    TestThisTwo:
      type: object
      properties:
        something:
          type: string
    TestThis:
      oneOf:
        - $ref: '#/components/schemas/TestThisOne'
        - $ref: '#/components/schemas/TestThisTwo'
tags:
  - name: exegesis
    description: Exegesis test
```
When I send following request bodies:
```json
{
  "title": "Something"
}
```
```json
{
  "title": "Something",
  "refs": "Some ref"
}
```
```json
{
  "something": "Something"
}
```
Exegesis will return a validation error with message "should match exactly one schema in oneOf".

All the above request bodies are fulfilling exactly one of allowed request schema so validation should not fail.

Validation will pass when *anyOf* is used in stead of *oneOf* but that allows mixing of two different request payloads.

**Comment by jwalton** [comment]
I fall into this trap all the time.  :P  The problem is that, for example, this message:

```
{
  "title": "Something"
}
```

really does not, in fact, match `oneOf` your two schemas, it matches both of them.  It matches `TestThisOne` because it has a title, and that title is a string (it also doesn't have a refs, but since there's no `required` section, it doesn't need to).  It also matches TestThisTwo because it doesn't have the optional `something` property either - `{}` would match TestThisTwo.  It *does* have this extra title property, but there's nothing in TestThisTwo which exludes extra properties, so that property just gets ignored.

To fix this, there's a few things you can do.  `anyOf` is one you already noted; if the object matches one or more of the schemas, it will be allowed through.  `anyOf` won't allow you to mix data from two different schemas, it'll just make it so if it matches two or more schemas it's still OK.  It still has to match at least one of them fully.  The other thing to do is to make these schemas mutually exclusive (which is what you probably want).  Something like:

```yaml
components:
  schemas:
    TestThisOne:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        refs:
          type: string
          nullable: true
    TestThisTwo:
      type: object
      required:
        - something
      properties:
        something:
          type: string
    TestThis:
      oneOf:
        - $ref: '#/components/schemas/TestThisOne'
        - $ref: '#/components/schemas/TestThisTwo'
```

would fix it, because now you need to have a `{title, refs?}` or a `{something}`, and these two types don't overlap at all.  You could also do:

```yaml
components:
  schemas:
    TestThisOne:
      type: object
      properties:
        title:
          type: string
        refs:
          type: string
          nullable: true
      additionalProperties: false
    TestThisTwo:
      type: object
      properties:
        something:
          type: string
      additionalProperties: false
    TestThis:
      oneOf:
        - $ref: '#/components/schemas/TestThisOne'
        - $ref: '#/components/schemas/TestThisTwo'
```

which will disallow extra properties on these objects, so then any object with a `title` would fail TestThisTwo, and any object with a `something` would fail ThisTestOne, so again they are mutually exclusive.  This isn't a great solution though, especially if this is a response schema, because it makes it much harder to add extra properties to these objects later on when you want to extend your API.  You'll break all the existing clients, who will reject the extra properties because of `additionalProperties: false`.

**Comment by jwalton** [comment]
Actually, I see what you mean about "mixing schemas".  If you had:

```yaml
components:
  schemas:
    TestThisOne:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        refs:
          type: string
          nullable: true
    TestThisTwo:
      type: object
      required:
        - something
      properties:
        something:
          type: string
    TestThis:
      anyOf:
        - $ref: '#/components/schemas/TestThisOne'
        - $ref: '#/components/schemas/TestThisTwo'
```

then:

```json
{
    "message": "foo",
    "something": "bar",
}
```

would pass through because of the anyOf - it again matches both, and we probably don't want that.  So you do want oneOf.  You just need to add some required fields to disambiguate your types.

**Comment by pawelusfr** [comment]
Thanks for the explanation @jwalton. In my case it's a `patch` request so required properties is not an option as it will be used for partial updates.

I know it's not the greatest API design to allow 2 separate schemas for partial updates from one endpoint but I don't have any other choice here (yay for a 3rd party database that mixes them as well).

I'm not sure about those required properties though. I took a look at [Swagger docs](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#oneof) and their examples are using `oneOf` with schemes without required properties. Those examples would fail your validation if I'm not mistaken

**Comment by jwalton** [comment]
Hmm...  I'm pretty sure Swagger's example is also broken.  -_-

Exegesis uses [ajv](https://github.com/epoberezkin/ajv) to do schema validation, so you can easily try stuff out with something like (adapted from [this](https://jsfiddle.net/ppoo24/fckyt5rm/)):

```js
const schema = {
    "type": "object",
    "oneOf": [
        {type: 'object', properties: {foo: {type: 'string'}}},
        {type: 'object', properties: {bar: {type: 'string'}}}
    ]
};
const json = {
  foo: 'hello'
};
const ajv = new Ajv({
	coerceTypes: true,
	useDefaults: true,
	removeAdditional: 'all'
});
const validate = ajv.compile(schema);
const result = validate(json);
console.log('Result: ', result);
console.log('Errors: ', validate.errors);
console.log('Final Json: ', json);
```

(You can see exactly the options we pass to ajv [here](https://github.com/exegesis-js/exegesis/blob/master/src/oas3/Schema/validators.ts#L217-L224).)

A few other suggestions; you could do something like:

```yaml
    TestThisOne:
      type: object
      properties:
        title:
          type: string
        refs:
          type: string
          nullable: true
        something:
          type: null
    TestThisTwo:
      type: object
      properties:
        title:
          type: null
        refs:
          type: null
        something:
          type: string
```

So now, if you provide an object like `{"title": "foo"}`, for example, it'll pass TestThisOne, but it will fail TestThisTwo (since in TestThisTwo, title has to be missing or null).  This doesn't quite work for your example because `refs` is already nullable, so `{"refs": null}` matches both schemas.

I would normally suggest adding some sort of single-value enum to both of these:

```yaml
    TestThisOne:
      type: object
      properties:
        type:
          type: string
          enum: ["TestThisOne"]
```

And then you have something to differentiate them, but since your doing a PATCH, you probably can't do that.  Maybe you really do want `additionalProperties: false` here.

**Comment by pawelusfr** [comment]
Thanks @jwalton. I have closed this based on your responses
