### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pvince** [exegesis-js/exegesis#16]
Does this project have a license it is being released under?

**Comment by jwalton** [comment]
It's MIT (specified in the package.json, but I should add a LICENSE file).

On Jun 4, 2018 10:01, "Paul Vincent" <notifications@github.com> wrote:

Does this project have a license it is being released under?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/exegesis-js/exegesis/issues/16>, or mute the thread

**Comment by jwalton** [comment]
License added here: https://github.com/exegesis-js/exegesis/commit/4781f6c19fadabef224b27a568826402ebd7e156
