### ISSUE TITLE
How to do testing of an Exegesis API

### ISSUE THREAD

**Issue by Ryan-Gordon** [exegesis-js/exegesis#22]
I have been building out an API which utilises Exegesis to map an OpenAPI doc to routes. I am wondering how this can be tested, given the setup of Exegesis is a little different than a normal Express API. It would be great to have some resource to reference on how testing can be done.

As a Exegesis API developer
I want a streamlined way to test my routes
So that automated testing can be done on the routes; This would allow for CI/CD testing also.
 
Acceptance Criteria: 
 
Scenario 1: 
Given a number of controllers in the controllers folder
  And each of these routes mapped to a OpenAPI path
When  it comes to testing
There should be a boilerplate that can be followed or some documentation

I can help with this but would need some guidance on where to start.

**Comment by Ryan-Gordon** [comment]
I have seen testing resources in this repo https://github.com/exegesis-js/exegesis-express/tree/master/test

Would the preferred way to test be : 
+ CreateServer, having a server created in the testing file 
+ Mock up 1 or 2 routes with an OpenAPI spec 
+ Then describe tests

**Comment by jwalton** [comment]
This is how I've been [doing my tests](https://github.com/exegesis-js/exegesis-express/blob/master/test/integrationTest.ts#L63-L69).  I'm using "supertest-fetch" here, which is a library I wrote with a fetch-like interface (mainly I wrote it because the Typescript bindings for supertest are broken.  :P)

Supertest (or supertest-fetch) will spin up a server for us on a random port, so I create a server with my exegesis controllers, then I just run tests against the server.

You could instantiate your controllers with some sort of IoC framework, and then it would be easy to stub out all the back-end logic and just test your controllers.  You could also test your controllers in isolation without involving Exegesis at all, although one upside to using Exegesis is you get request and response validation more-or-less for free, which is nice.
