### ISSUE TITLE
update promise-breaker dep. break build

### ISSUE THREAD

**Issue by KrakenTyio** [exegesis-js/exegesis#59]
```
"promise-breaker": "^4.1.11"
```
is broken, bc. it install version 4.1.13 when you reinstall deps.
with this version i get error in build process
```
> tsc

src/index.ts:185:25 - error TS2345: Argument of type 'Callback<MiddlewareFunction> | undefined' is not assignable to parameter of type 'Callback<(ctx: Context, next: Callback<void>) => Promise<void>> | null | undefined'.
  Type 'Callback<MiddlewareFunction>' is not assignable to type 'Callback<(ctx: Context, next: Callback<void>) => Promise<void>> | null | undefined'.
    Type 'Callback<MiddlewareFunction>' is not assignable to type 'Callback<(ctx: Context, next: Callback<void>) => Promise<void>>'.
      Types of parameters 'value' and 'result' are incompatible.
        Types of parameters 'next' and 'next' are incompatible.
          Type 'Callback<void> | undefined' is not assignable to type 'Callback<void>'.
            Type 'undefined' is not assignable to type 'Callback<void>'.

185   return pb.addCallback(done, async () => {
          
```

also package-lock.json should`nt be gitted.

**Comment by jwalton** [comment]
Sorry I missed this issue, but the good news is I fixed it in Feb.

> also package-lock.json should`nt be gitted.

I agree with you, although `npm version patch` tried to add it, so if you have it in your .gitignore, `npm version` will fail.  -_-  I suppose that's not really an issue on this project, since we're using semantic-release.

I've always kind of wondered what the point of package-lock.json is.  It's useful in an application (as opposed to a library) since it locks all your dependencies, but there was always npm-shrinkwrap.json for that.  For a library, it doesn't really make sense, since it doesn't affect anyone other than you when you're developing the library, and it just means you'll get out-of-date dependencies compared to what other people will get.
