### ISSUE TITLE
When is approx. RTM 1.0 date?

### ISSUE THREAD

**Issue by arvind-agarwal** [exegesis-js/exegesis#7]
Really like this project, since currently there are no other alternatives to swagger-tools and swagger-node for OpenAPI 3.0, this seems like a great project.

I want to use it for one of my projects, but before I go on that journey wanted to understand your plans for 1.0 release.

**Comment by jwalton** [comment]
Hey, thanks for the interest.  I hear you about there being no alternatives, that's why I'm writing this.  :)

I'm hoping to go 1.0 in the next couple of weeks.  I'm developing this in parallel with a project that's using it, which is going to go live sometime in the next couple of weeks.

Things that are probably going to change in the API before 1.0:

* Right now authenticators just take in the context as an argument, but it would be nice to pass the security scheme in as well.
* Exegesis supports this concept of [roles](https://github.com/exegesis-js/exegesis/blob/master/docs/OAS3%20Specification%20Extensions.md#x-exegesis-roles), but I've been doing a little work to refactor this out into a ["plugin"](https://github.com/exegesis-js/exegesis/blob/master/src/oas3/plugins/RolesPlugin.ts), so likely by 1.0 you'll need to include a plugin in your options to get that functionality.
* #2 will be fixed.  It would be nice to fix #1, but I feel like it's a more esoteric use case and I can wait until later.
* Response validation is talked about in the docs, but it's not implemented yet, and it will be there very soon.
* I'm aiming for at least 90% test coverage.

So, if you can live with all of that, feel free to dig in and try stuff out.  There's a bunch of [documentation here](https://github.com/exegesis-js/exegesis/tree/master/docs).  If you find anything unclear I'd like to know.  :)

This is also my first typescript project, so if you know typescript, feel free to point out all the horrible typescript faux-pas I've made.  :P  And if you don't know typescript, I'm really enjoying it, so give it a try.  :)

**Comment by arvind-agarwal** [comment]
Hi @jwalton, Thanks for detailed reply. This sounds perfect. I am hoping you are planning to maintain this beyond your project also. I will definitely give this a try.

Regarding TypeScript, I have not yet ventured into that territory. Somehow I don't like using Transpilers on Node side. Maybe someday I will get over that mental block.

Thanks.

**Comment by jwalton** [comment]
The project I'm building this for is called [Loop](https://www.benbria.com/).  It's my company's main product, and I've been working on it for five years.  Hopefully I'll be working on it a bit longer.  :)

I hear you about transpiling Javascript.  Our company made a big early investment into coffee-script, and now we have several hundred coffee-script files, but upgrading to the latest coffee-script breaks everything.  -_-  We've been slowly converting out .coffee files to .js.  I was long reluctant to try another transpiled language after that (aside from using Babel to turn JS into JS).  But one of the things I really like about Typescript is that it's essentially a super-set of JS.  If you run the TS compiler and "target" the latest Javascript, it basically just takes out all the type annotations, leaving you with code that's basically exactly the same as the JS you would have written if you weren't using TS, comments and all.  So if Microsoft screws this all up and makes a hash of TS, you have an escape route.  :)

**Comment by arvind-agarwal** [comment]
Your product looks very interesting. Good work @jwalton

**Comment by jwalton** [comment]
Well, Loop is certainly not just my work, by thanks.  :)
